export const DISCOUNT_PERCENT = Symbol('DISCOUNT_PERCENT');

export const OWNERS_TO_DELETE_PERIOD_IN_MONTH = 18;

export const CAR_PERIOD_START_TO_APPLY_DISCOUNT_IN_MONTH = 18;
export const CAR_PERIOD_END_TO_APPLY_DISCOUNT_IN_MONTH = 12;
